{{- if or .Values.rbac.enabled (eq .Values.mode "sentinel") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
rules:
  {{- if eq .Values.mode "sentinel" }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch"]
  {{- end }}
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
