apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  {{- with .Values.services.write.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.write.type }}
  {{- if .Values.services.write.clusterIP }}
  clusterIP: {{ .Values.services.write.clusterIP }}
  {{- end }}
  {{- if .Values.services.write.loadBalancerClass }}
  loadBalancerClass: {{ .Values.services.write.loadBalancerClass }}
  {{- end }}
  {{- if .Values.services.write.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .Values.services.write.loadBalancerSourceRanges }}
  {{- end }}
  ports:
    - port: {{ .Values.services.write.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
      {{- if and (eq .Values.services.write.type "NodePort") .Values.services.write.nodePort }}
      nodePort: {{ .Values.services.write.nodePort }}
      {{- end }}
      {{- if .Values.services.write.appProtocol }}
      appProtocol: {{ .Values.services.write.appProtocol }}
      {{- end }}
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
    {{- if ne .Values.mode "standalone" }}
    {{- if eq .Values.mode "sentinel" }}
    valkey-role: master
    {{- else }}
    statefulset.kubernetes.io/pod-name: {{ include "valkey.fullname" . }}-0
    {{- end }}
    {{- end }}
