{{- if and (ne .Values.mode "standalone") .Values.services.read.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}-read
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: read
  {{- with .Values.services.read.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.read.type }}
  {{- if .Values.services.read.clusterIP }}
  clusterIP: {{ .Values.services.read.clusterIP }}
  {{- end }}
  {{- if .Values.services.read.loadBalancerClass }}
  loadBalancerClass: {{ .Values.services.read.loadBalancerClass }}
  {{- end }}
  {{- if .Values.services.read.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .Values.services.read.loadBalancerSourceRanges }}
  {{- end }}
  ports:
    - name: tcp
      port: {{ .Values.services.read.port }}
      targetPort: tcp
      protocol: TCP
      {{- if and (eq .Values.services.read.type "NodePort") .Values.services.read.nodePort }}
      nodePort: {{ .Values.services.read.nodePort }}
      {{- end }}
      {{- if .Values.services.read.appProtocol }}
      appProtocol: {{ .Values.services.read.appProtocol }}
      {{- end }}
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
    {{- if eq .Values.mode "sentinel" }}
    valkey-role: replica
    {{- end }}
{{- end }}
