{{- if and (eq .Values.mode "sentinel") .Values.services.sentinel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}-sentinel
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
  {{- with .Values.services.sentinel.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.sentinel.type }}
  {{- if .Values.services.sentinel.clusterIP }}
  clusterIP: {{ .Values.services.sentinel.clusterIP }}
  {{- end }}
  ports:
    - name: sentinel
      port: {{ .Values.services.sentinel.port | default .Values.sentinel.port }}
      targetPort: sentinel
      protocol: TCP
      {{- if and (eq .Values.services.sentinel.type "NodePort") .Values.services.sentinel.nodePort }}
      nodePort: {{ .Values.services.sentinel.nodePort }}
      {{- end }}
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
{{- end }}
